### ISSUE TITLE
Importing a list of freight cars fails if CR (0x0d) used for end of line character

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bowdidge/switchlist#75]
```
Create a text file listing boxcars, but use 0x0d instead of 0x0a for the end of 
line character.  

Import the file.  It fails, only loading one car.

SwitchList should handle such files as well as Windows files correctly.
```

---

Original issue reported on code.google.com by `rwbowdi...@gmail.com` on 30 Sep 2014 at 2:51

**Comment by bowdidge** [comment]
This was only a problem for files exported from a Mac version of Excel which used the old Mac format (\r) instead of the Unix line ending (\n).  Windows should be ok because it'll normally give a \r\n which should distinguish the lines.

Only one case of this affecting someone in the field.  Closing unless I get more reports.
